builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/vale/main.go
    binary: vale
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
