builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/vale
    binary: vale
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64-bit
      darwin: macOS
      linux: Linux
      windows: Windows
