name: Bump Packages

on: push

jobs:
  get-version:
    name: Get Version
    runs-on: ubuntu-18.04
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

  bump-packages:
    needs: [get-version]
    runs-on: ubuntu-18.04
    steps:
      - name: Trigger Bump
        uses: peter-evans/repository-dispatch@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: bump-pkg
          repository: errata-ai/install
          client-payload: '{"version": "${{ needs.get-version.outputs.version }}"}'