name: Build + Lint

on: push

jobs:
  get-version:
    name: Get Version
    runs-on: ubuntu-18.04
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get version
        id: get_version
        run: |
          version=""
          if [ "${{ github.event_name }}" == "repository_dispatch" ]
          then
            version="${{ github.event.client_payload.tag }}"
          else
            version="${{ github.event.inputs.version }}"
          fi
          echo "::set-output name=version::$version"

  bump-packages:
    needs: [get-version]
    runs-on: ubuntu-18.04
    steps:
      - name: Trigger Bump
        uses: peter-evans/repository-dispatch@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: bump-pkg
          repository: errata-ai/install
          client-payload: '{"version": "${{ needs.get-version.outputs.version }}"}'

  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: errata-ai/vale-action@reviewdog
        with:
          debug: true
          fail_on_error: true
          reporter: github-check
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
